task: cont_state_llm_num_optim_semantics
num_episodes: 100
gym_env_name: RoboSuiteLiftDiscrete-v0
render_mode: null
logdir: logs/robosuite_lift_propsp
dim_actions: 9
dim_states: 64
max_traj_count: 256
max_traj_length: 200
template_dir: agent/policy/templates
llm_si_template_name: num_optim_semantics.j2
llm_output_conversion_template_name: num_optim_semantics.j2
llm_model_name: gpt-4o
num_evaluation_episodes: 5
warmup_episodes: 10
warmup_dir: null
bias: true
optimum: 300
search_step_size: 0.5
env_desc_file: env_descriptions/robosuite_lift_discrete.j2
env_kwargs:
  env_name: Lift
  robot: Panda
  camera_name: agentview
  horizon: 200
  reward_shaping: true
  state_dim: 64
  translation_delta: 1.0
  gripper_open_value: -1.0
  gripper_close_value: 1.0
  state_keys:
    - robot0_proprio-state
    - object-state
