task: cont_space_mu_lambda_es
num_episodes: 300
gym_env_name: fancy/LongSimpleReacher-v0
render_mode: null
dim_actions: 5
dim_states: 18
max_traj_count: 1000
max_traj_length: 200
num_evaluation_episodes: 20
warmup_episodes: 0
warmup_dir: null
bias: true
logdir: logs/fancy_long_simple_reacher_mu_lambda_es
mu: 16
lam: 32
sigma: 0.1
sigma_decay: 1.0
min_sigma: 1.0e-12
max_sigma: null
param_bound: 10.0
cxmode: blend
alpha: 0.5
cxpb: 0.6
mutpb: 0.3
smin: 0.01
smax: 0.5
clip: true
ncores: 1
candidate_evaluation_episodes: 1
