task: cont_state_llm_num_optim_vision_oneshot
num_episodes: 400
gym_env_name: LunarLander-v3
render_mode: rgb_array
logdir: logs/lunarlander_discrete_propsv_oneshot
dim_actions: 4
dim_states: 8
max_traj_count: 1000
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: num_optim_vision.j2
llm_output_conversion_template_name: num_optim_vision.j2
llm_model_name: openrouter/openai/gpt-oss-120b:free
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
bias: true
optimum: 200
search_step_size: 0.1
env_desc_file: env_descriptions/lunarlander_discrete.j2

# ProPS-V OneShot specific parameters
vlm_model_name: gpt-4o
decay_horizon: 100
frame_sample_period: 50
n_neighbors: 5
poisson_lam: 2.0
neighbor_step: 0.1
enable_vision: true
