task: dist_state_mu_lambda_es_qvalue
num_episodes: 300
gym_env_name: CliffWalking-v0
render_mode: null
dim_actions:
- - 0
  - 1
  - 2
  - 3
dim_states:
- - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 33
  - 34
  - 35
  - 36
  - 37
  - 38
  - 39
  - 40
  - 41
  - 42
  - 43
  - 44
  - 45
  - 46
  - 47
max_traj_count: 1000
max_traj_length: 100
num_evaluation_episodes: 20
warmup_episodes: 0
warmup_dir: null
bias: true
env_kwargs:
  is_slippery: true
logdir: logs/cliffwalking_mu_lambda_es_qvalue
mu: 16
lam: 32
sigma: 0.1
sigma_decay: 1.0
min_sigma: 1.0e-12
max_sigma: null
param_bound: 10.0
cxmode: blend
alpha: 0.5
cxpb: 0.6
mutpb: 0.3
smin: 0.01
smax: 0.5
clip: true
ncores: 1
candidate_evaluation_episodes: 1
