task: cont_space_ars
num_episodes: 100
gym_env_name: Grid2OpCase14-v0
render_mode: null
dim_actions: 41
dim_states: 40
max_traj_count: 1
max_traj_length: 100
num_evaluation_episodes: 5
warmup_episodes: 0
warmup_dir: null
bias: true
env_kwargs:
  grid2op_env_name: l2rpn_case14_sandbox
  reward_class_name: L2RPNReward
  observation_features:
  - rho
  - line_status
logdir: logs/grid2op_case14_ars
n_directions: 16
deltas_used: 8
step_size: 0.03
delta_std: 0.1
shift: 0.0
candidate_evaluation_episodes: 1
reward_normalization_epsilon: 1.0e-08
grad_batch_size: 500
